In [164]:
# import kagglehub

# # Download latest version
# path = kagglehub.competition_download('spaceship-titanic',output_dir='./data/')

# print("Path to competition files:", path)

In [165]:
import pandas as pd

In [166]:
df_train = pd.read_csv('./data/train.csv')
df_test = pd.read_csv('./data/test.csv')

In [167]:
df_train.shape

(8693, 14)

In [168]:
df_test.shape

(4277, 13)

In [169]:
df_train.head()

,PassengerId,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Name,Transported
0,0001_01,Europa,False,B/0/P,TRAPPIST-1e,39.0,False,0.0,0.0,0.0,0.0,0.0,Maham Ofracculy,False
1,0002_01,Earth,False,F/0/S,TRAPPIST-1e,24.0,False,109.0,9.0,25.0,549.0,44.0,Juanna Vines,True
2,0003_01,Europa,False,A/0/S,TRAPPIST-1e,58.0,True,43.0,3576.0,0.0,6715.0,49.0,Altark Susent,False
3,0003_02,Europa,False,A/0/S,TRAPPIST-1e,33.0,False,0.0,1283.0,371.0,3329.0,193.0,Solam Susent,False
4,0004_01,Earth,False,F/1/S,TRAPPIST-1e,16.0,False,303.0,70.0,151.0,565.0,2.0,Willy Santantines,True

In [170]:
df_test.head()

,PassengerId,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Name
0,0013_01,Earth,True,G/3/S,TRAPPIST-1e,27.0,False,0.0,0.0,0.0,0.0,0.0,Nelly Carsoning
1,0018_01,Earth,False,F/4/S,TRAPPIST-1e,19.0,False,0.0,9.0,0.0,2823.0,0.0,Lerome Peckers
2,0019_01,Europa,True,C/0/S,55 Cancri e,31.0,False,0.0,0.0,0.0,0.0,0.0,Sabih Unhearfus
3,0021_01,Europa,False,C/1/S,TRAPPIST-1e,38.0,False,0.0,6652.0,0.0,181.0,585.0,Meratz Caltilter
4,0023_01,Earth,False,F/5/S,TRAPPIST-1e,20.0,False,10.0,0.0,635.0,0.0,0.0,Brence Harperez

In [171]:
df_train.columns

Index(['PassengerId', 'HomePlanet', 'CryoSleep', 'Cabin', 'Destination', 'Age',
       'VIP', 'RoomService', 'FoodCourt', 'ShoppingMall', 'Spa', 'VRDeck',
       'Name', 'Transported'],
      dtype='str')

In [172]:
df_train.columns[df_train.dtypes != 'float64']

Index(['PassengerId', 'HomePlanet', 'CryoSleep', 'Cabin', 'Destination', 'VIP',
       'Name', 'Transported'],
      dtype='str')

In [173]:
c_train=df_train.drop(columns=['PassengerId'])

In [174]:
c_test=df_test.drop(columns=['PassengerId'])

In [175]:
c_train.columns[c_train.dtypes != 'float64']

Index(['HomePlanet', 'CryoSleep', 'Cabin', 'Destination', 'VIP', 'Name',
       'Transported'],
      dtype='str')

In [176]:
print(c_train['HomePlanet'].value_counts())
print(c_train['CryoSleep'].value_counts())
print(c_train['Destination'].value_counts())
print(c_train['VIP'].value_counts())
print(f"nunique name: {c_train['Name'].nunique()}")
print(f"nunique cabin: {c_train['Cabin'].nunique()}")

HomePlanet
Earth     4602
Europa    2131
Mars      1759
Name: count, dtype: int64
CryoSleep
False    5439
True     3037
Name: count, dtype: int64
Destination
TRAPPIST-1e      5915
55 Cancri e      1800
PSO J318.5-22     796
Name: count, dtype: int64
VIP
False    8291
True      199
Name: count, dtype: int64
nunique name: 8473
nunique cabin: 6560

In [177]:
c_train=c_train.drop(columns=['Cabin','Name'])

In [178]:
c_test=c_test.drop(columns=['Cabin','Name'])

In [ ]:
c_train=pd.get_dummies(c_train, columns=['HomePlanet','CryoSleep','Destination','VIP','Transported'], drop_first=True,dtype=float)

In [ ]:
c_test=pd.get_dummies(c_test, columns=['HomePlanet','CryoSleep','Destination','VIP','Transported'], drop_first=True,dtype=float)

In [181]:
c_train.columns[c_train.dtypes != 'float64']

Index(['Transported'], dtype='str')

In [183]:
c_train.shape[1]==c_test.shape[1]+1

True

In [184]:
c_train['Transported'].value_counts()

Transported
True     4378
False    4315
Name: count, dtype: int64